package com.xstd.phoneService.model.send;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.phoneService.model.send.SMSSent;

import com.xstd.phoneService.model.send.SMSSentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sMSSentDaoConfig;

    private final SMSSentDao sMSSentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sMSSentDaoConfig = daoConfigMap.get(SMSSentDao.class).clone();
        sMSSentDaoConfig.initIdentityScope(type);

        sMSSentDao = new SMSSentDao(sMSSentDaoConfig, this);

        registerDao(SMSSent.class, sMSSentDao);
    }
    
    public void clear() {
        sMSSentDaoConfig.getIdentityScope().clear();
    }

    public SMSSentDao getSMSSentDao() {
        return sMSSentDao;
    }

}
