package com.xstd.phoneService.model.send;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SMSSENT.
 */
public class SMSSent implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    /** Not-null value. */
    private String from;
    /** Not-null value. */
    private String imei;
    /** Not-null value. */
    private String phoneType;
    private String networkType;
    private long receiveTime;
    private long sendTime;
    /** Not-null value. */
    private String sendPhoneNumber;
    private String extra;
    private String extra1;
    private String extra2;

    public SMSSent() {
    }

    public SMSSent(Long id, String from) {
        this.id = id;
        this.from = from;
    }

    public SMSSent(Long id, String from, String imei, String phoneType, String networkType, long receiveTime, long sendTime, String sendPhoneNumber, String extra, String extra1, String extra2) {
        this.id = id;
        this.from = from;
        this.imei = imei;
        this.phoneType = phoneType;
        this.networkType = networkType;
        this.receiveTime = receiveTime;
        this.sendTime = sendTime;
        this.sendPhoneNumber = sendPhoneNumber;
        this.extra = extra;
        this.extra1 = extra1;
        this.extra2 = extra2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFrom() {
        return from;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFrom(String from) {
        this.from = from;
    }

    /** Not-null value. */
    public String getImei() {
        return imei;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /** Not-null value. */
    public String getPhoneType() {
        return phoneType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType;
    }

    public String getNetworkType() {
        return networkType;
    }

    public void setNetworkType(String networkType) {
        this.networkType = networkType;
    }

    public long getReceiveTime() {
        return receiveTime;
    }

    public void setReceiveTime(long receiveTime) {
        this.receiveTime = receiveTime;
    }

    public long getSendTime() {
        return sendTime;
    }

    public void setSendTime(long sendTime) {
        this.sendTime = sendTime;
    }

    /** Not-null value. */
    public String getSendPhoneNumber() {
        return sendPhoneNumber;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSendPhoneNumber(String sendPhoneNumber) {
        this.sendPhoneNumber = sendPhoneNumber;
    }

    public String getExtra() {
        return extra;
    }

    public void setExtra(String extra) {
        this.extra = extra;
    }

    public String getExtra1() {
        return extra1;
    }

    public void setExtra1(String extra1) {
        this.extra1 = extra1;
    }

    public String getExtra2() {
        return extra2;
    }

    public void setExtra2(String extra2) {
        this.extra2 = extra2;
    }

    @Override
    public String toString() {
        return "[SMSSent]" + "id = " + id + ", " + "from = " + from + ", " + "imei = " + imei + ", " + "phoneType = " + phoneType + ", " + "networkType = " + networkType + ", " + "receiveTime = " + receiveTime + ", " + "sendTime = " + sendTime + ", " + "sendPhoneNumber = " + sendPhoneNumber + ", " + "extra = " + extra + ", " + "extra1 = " + extra1 + ", " + "extra2 = " + extra2 + "\r\n";
    }

}
