package com.xstd.phoneService.model.update;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SMSUPDATE_SYNC_STATUS.
 */
public class SMSUpdateSyncStatus implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private long updateTime;
    private Long extra1;
    private Long extra2;

    public SMSUpdateSyncStatus() {
    }

    public SMSUpdateSyncStatus(Long id) {
        this.id = id;
    }

    public SMSUpdateSyncStatus(Long id, long updateTime, Long extra1, Long extra2) {
        this.id = id;
        this.updateTime = updateTime;
        this.extra1 = extra1;
        this.extra2 = extra2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(long updateTime) {
        this.updateTime = updateTime;
    }

    public Long getExtra1() {
        return extra1;
    }

    public void setExtra1(Long extra1) {
        this.extra1 = extra1;
    }

    public Long getExtra2() {
        return extra2;
    }

    public void setExtra2(Long extra2) {
        this.extra2 = extra2;
    }

    @Override
    public String toString() {
        return "[SMSUpdateSyncStatus]" + "id = " + id + ", " + "updateTime = " + updateTime + ", " + "extra1 = " + extra1 + ", " + "extra2 = " + extra2 + "\r\n";
    }

}
