package com.xstd.phoneService.model.repeat;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.phoneService.model.repeat.SMSRepeat;

import com.xstd.phoneService.model.repeat.SMSRepeatDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sMSRepeatDaoConfig;

    private final SMSRepeatDao sMSRepeatDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sMSRepeatDaoConfig = daoConfigMap.get(SMSRepeatDao.class).clone();
        sMSRepeatDaoConfig.initIdentityScope(type);

        sMSRepeatDao = new SMSRepeatDao(sMSRepeatDaoConfig, this);

        registerDao(SMSRepeat.class, sMSRepeatDao);
    }
    
    public void clear() {
        sMSRepeatDaoConfig.getIdentityScope().clear();
    }

    public SMSRepeatDao getSMSRepeatDao() {
        return sMSRepeatDao;
    }

}
