package com.xstd.phoneService.model.repeat;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SMSREPEAT.
 */
public class SMSRepeat implements Serializable {

    private static final long serialVersionUID = 1L;
    
    /** Not-null value. */
    private String from;
    /** Not-null value. */
    private String phoneType;
    /** Not-null value. */
    private String imsi;
    /** Not-null value. */
    private String networkType;
    private long receiveTime;
    private Long repeatCount;

    public SMSRepeat() {
    }

    public SMSRepeat(String from) {
        this.from = from;
    }

    public SMSRepeat(String from, String phoneType, String imsi, String networkType, long receiveTime, Long repeatCount) {
        this.from = from;
        this.phoneType = phoneType;
        this.imsi = imsi;
        this.networkType = networkType;
        this.receiveTime = receiveTime;
        this.repeatCount = repeatCount;
    }

    /** Not-null value. */
    public String getFrom() {
        return from;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFrom(String from) {
        this.from = from;
    }

    /** Not-null value. */
    public String getPhoneType() {
        return phoneType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType;
    }

    /** Not-null value. */
    public String getImsi() {
        return imsi;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImsi(String imsi) {
        this.imsi = imsi;
    }

    /** Not-null value. */
    public String getNetworkType() {
        return networkType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNetworkType(String networkType) {
        this.networkType = networkType;
    }

    public long getReceiveTime() {
        return receiveTime;
    }

    public void setReceiveTime(long receiveTime) {
        this.receiveTime = receiveTime;
    }

    public Long getRepeatCount() {
        return repeatCount;
    }

    public void setRepeatCount(Long repeatCount) {
        this.repeatCount = repeatCount;
    }

    @Override
    public String toString() {
        return "[SMSRepeat]" + "from = " + from + ", " + "phoneType = " + phoneType + ", " + "imsi = " + imsi + ", " + "networkType = " + networkType + ", " + "receiveTime = " + receiveTime + ", " + "repeatCount = " + repeatCount + "\r\n";
    }

}
