package com.xstd.phoneService.model.receive;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.phoneService.model.receive.SMSReceived;

import com.xstd.phoneService.model.receive.SMSReceivedDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sMSReceivedDaoConfig;

    private final SMSReceivedDao sMSReceivedDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sMSReceivedDaoConfig = daoConfigMap.get(SMSReceivedDao.class).clone();
        sMSReceivedDaoConfig.initIdentityScope(type);

        sMSReceivedDao = new SMSReceivedDao(sMSReceivedDaoConfig, this);

        registerDao(SMSReceived.class, sMSReceivedDao);
    }
    
    public void clear() {
        sMSReceivedDaoConfig.getIdentityScope().clear();
    }

    public SMSReceivedDao getSMSReceivedDao() {
        return sMSReceivedDao;
    }

}
