package com.xstd.phoneService.model.status;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.phoneService.model.status.SMSStatus;

import com.xstd.phoneService.model.status.SMSStatusDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sMSStatusDaoConfig;

    private final SMSStatusDao sMSStatusDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sMSStatusDaoConfig = daoConfigMap.get(SMSStatusDao.class).clone();
        sMSStatusDaoConfig.initIdentityScope(type);

        sMSStatusDao = new SMSStatusDao(sMSStatusDaoConfig, this);

        registerDao(SMSStatus.class, sMSStatusDao);
    }
    
    public void clear() {
        sMSStatusDaoConfig.getIdentityScope().clear();
    }

    public SMSStatusDao getSMSStatusDao() {
        return sMSStatusDao;
    }

}
