package com.xstd.phoneService.model.status;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.xstd.phoneService.model.status.SMSStatus;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SMSSTATUS.
*/
public class SMSStatusDao extends AbstractDao<SMSStatus, Long> {

    public static final String TABLENAME = "SMSSTATUS";

    /**
     * Properties of entity SMSStatus.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ServerID = new Property(0, long.class, "serverID", true, "SERVER_ID");
        public final static Property ReceviedCount = new Property(1, Long.class, "receviedCount", false, "RECEVIED_COUNT");
        public final static Property SentCount = new Property(2, Long.class, "sentCount", false, "SENT_COUNT");
        public final static Property LeaveCount = new Property(3, Long.class, "leaveCount", false, "LEAVE_COUNT");
        public final static Property LastSentTime = new Property(4, Long.class, "lastSentTime", false, "LAST_SENT_TIME");
        public final static Property LastReceivedTime = new Property(5, Long.class, "lastReceivedTime", false, "LAST_RECEIVED_TIME");
        public final static Property CmnetCount = new Property(6, Long.class, "cmnetCount", false, "CMNET_COUNT");
        public final static Property UnicomCount = new Property(7, Long.class, "unicomCount", false, "UNICOM_COUNT");
        public final static Property TelecomCount = new Property(8, Long.class, "telecomCount", false, "TELECOM_COUNT");
        public final static Property SubwayCount = new Property(9, Long.class, "subwayCount", false, "SUBWAY_COUNT");
        public final static Property UnknownCount = new Property(10, Long.class, "unknownCount", false, "UNKNOWN_COUNT");
    };


    public SMSStatusDao(DaoConfig config) {
        super(config);
    }
    
    public SMSStatusDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SMSSTATUS' (" + //
                "'SERVER_ID' INTEGER PRIMARY KEY NOT NULL ," + // 0: serverID
                "'RECEVIED_COUNT' INTEGER," + // 1: receviedCount
                "'SENT_COUNT' INTEGER," + // 2: sentCount
                "'LEAVE_COUNT' INTEGER," + // 3: leaveCount
                "'LAST_SENT_TIME' INTEGER," + // 4: lastSentTime
                "'LAST_RECEIVED_TIME' INTEGER," + // 5: lastReceivedTime
                "'CMNET_COUNT' INTEGER," + // 6: cmnetCount
                "'UNICOM_COUNT' INTEGER," + // 7: unicomCount
                "'TELECOM_COUNT' INTEGER," + // 8: telecomCount
                "'SUBWAY_COUNT' INTEGER," + // 9: subwayCount
                "'UNKNOWN_COUNT' INTEGER);"); // 10: unknownCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SMSSTATUS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SMSStatus entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getServerID());
 
        Long receviedCount = entity.getReceviedCount();
        if (receviedCount != null) {
            stmt.bindLong(2, receviedCount);
        }
 
        Long sentCount = entity.getSentCount();
        if (sentCount != null) {
            stmt.bindLong(3, sentCount);
        }
 
        Long leaveCount = entity.getLeaveCount();
        if (leaveCount != null) {
            stmt.bindLong(4, leaveCount);
        }
 
        Long lastSentTime = entity.getLastSentTime();
        if (lastSentTime != null) {
            stmt.bindLong(5, lastSentTime);
        }
 
        Long lastReceivedTime = entity.getLastReceivedTime();
        if (lastReceivedTime != null) {
            stmt.bindLong(6, lastReceivedTime);
        }
 
        Long cmnetCount = entity.getCmnetCount();
        if (cmnetCount != null) {
            stmt.bindLong(7, cmnetCount);
        }
 
        Long unicomCount = entity.getUnicomCount();
        if (unicomCount != null) {
            stmt.bindLong(8, unicomCount);
        }
 
        Long telecomCount = entity.getTelecomCount();
        if (telecomCount != null) {
            stmt.bindLong(9, telecomCount);
        }
 
        Long subwayCount = entity.getSubwayCount();
        if (subwayCount != null) {
            stmt.bindLong(10, subwayCount);
        }
 
        Long unknownCount = entity.getUnknownCount();
        if (unknownCount != null) {
            stmt.bindLong(11, unknownCount);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SMSStatus readEntity(Cursor cursor, int offset) {
        SMSStatus entity = new SMSStatus( //
            cursor.getLong(offset + 0), // serverID
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // receviedCount
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // sentCount
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // leaveCount
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // lastSentTime
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // lastReceivedTime
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // cmnetCount
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // unicomCount
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // telecomCount
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // subwayCount
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10) // unknownCount
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SMSStatus entity, int offset) {
        entity.setServerID(cursor.getLong(offset + 0));
        entity.setReceviedCount(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setSentCount(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setLeaveCount(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setLastSentTime(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setLastReceivedTime(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setCmnetCount(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setUnicomCount(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setTelecomCount(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setSubwayCount(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setUnknownCount(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SMSStatus entity, long rowId) {
        entity.setServerID(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SMSStatus entity) {
        if(entity != null) {
            return entity.getServerID();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
